feat: add support for service account expiry in job configuration

diff --git a/chart/templates/job.yaml b/chart/templates/job.yaml
--- a/chart/templates/job.yaml
+++ b/chart/templates/job.yaml
@@ -49,7 +49,13 @@ spec:
             {{- if $sa.secretKey }}
             opts="$opts --secret-key ${{ $sa.secretKey }}"
             {{- end }}
-            mc admin user svcacct add $opts --policy /tmp/{{ $sa.name }}-policy.json myminio {{ $sa.name }};
+            {{- if $sa.expiry }}
+            opts="$opts --expiry ${{ $sa.expiry }}"
+            {{- end }}
+            mc admin user svcacct add $opts --policy /tmp/{{ $sa.name }}-policy.json myminio {{ $sa.name }} &>/dev/null &
+            if [ $? -ne 0 ]; then
+              echo "Failed to create service account {{ $sa.name }}" >&2
+            fi
             {{- end }}
         env:
         - name: MINIO_SERVER
